general {
    lock_cmd = timeout 2s qs -p /home/Zrabbit/.config/quickshell/lockscreen ipc call lock lock || QUICKSHELL_LOCK_ON_START=1 qs -n -d -p /home/Zrabbit/.config/quickshell/lockscreen
    before_sleep_cmd = timeout 2s qs -p /home/Zrabbit/.config/quickshell/lockscreen ipc call lock prepareSuspend; sleep 0.25; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'; timeout 2s qs -p /home/Zrabbit/.config/quickshell/lockscreen ipc call lock resumeAfterSuspend

    inhibit_sleep = 3
}

listener {
    # 5 min
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    # 6 min
    timeout = 360
    on-timeout = timeout 2s qs -p /home/Zrabbit/.config/quickshell/lockscreen ipc call lock prepareSuspend && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'; timeout 2s qs -p /home/Zrabbit/.config/quickshell/lockscreen ipc call lock resumeAfterSuspend
}

listener {
    # 10 min
    timeout = 600
    condition_cmd = timeout 2s qs -p /home/Zrabbit/.config/quickshell/lockscreen ipc call lock status | jq -e '.secure == true' >/dev/null
    condition_retry = 1
    on-timeout = systemctl suspend
}
