# Colors
background = 0xCC0D0D0D
base = 0xFF141414
alternate_base = 0xFF1B1B1B
text = 0xFFD8D8D8
bright_text = 0xFFF2F2F2
accent = 0xFF2C2C2C
accent_secondary = 0xFF3A3A3A

# Fonts
h1_size = 19        
h2_size = 15            
h3_size = 13           
font_size = 11        
small_font_size = 10 

font_family = Atkinson Hyperlegible Next
font_family_monospace = JetBrainsMono Nerd Font

# Icons
icon_theme =

# Rounding
rounding_large = 12 # Default: 10
rounding_small = 8  # Default: 5
