#!/bin/sh
set -eu # Exit on error (-e) and on undefined variables (-u)

# Make sure it only spawn once
lockdir="${XDG_RUNTIME_DIR:?}/screenshot-locks"
mkdir -p "$lockdir"
lockfile="$lockdir/screenshot_window.lock"
exec 9>"$lockfile"
flock -n 9 || exit 0

# The remaining script
OUTDIR="$HOME/Pictures/Screenshots"
TMPDIR="$XDG_RUNTIME_DIR"
TS="$(date +%Y%m%d_%H%M%S_%3N)"
NAME="${TS}_grim.png"
TMPFILE="$TMPDIR/$NAME"
FINALFILE="$OUTDIR/$NAME"
BODY="$(printf '<img src="file://%s"/>\n%s' "$TMPFILE" "$NAME")"

geom="$(
  hyprctl -j clients |
    jq -r '.[]
      | select(.mapped == true)
      | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"
    ' |
    slurp
)" || exit 0

grim -g "$geom" "$TMPFILE"

CHOICE="$(
  notify-send \
    -a Screenshot \
    -t 9000 \
    -A save=Save \
    -A discard=Discard \
    -A edit=Edit \
    -A copy=Copy \
    -A saveshow='Save & Show' \
    -A savecopy='Save & Copy' \
    "Screenshot Captured" "$BODY"
)"

# Do not let wl-copy, swappy, or feh inherit the screenshot lock
flock -u 9
exec 9>&-

case "${CHOICE:-}" in
  discard)
    rm -f -- "$TMPFILE"
    ;;
  copy)
    wl-copy --type image/png < "$TMPFILE"
    rm -f -- "$TMPFILE"
    ;;
  edit)
    mv -f "$TMPFILE" "$FINALFILE"
    swappy -f "$FINALFILE"
    ;;
  saveshow)
    mv -f "$TMPFILE" "$FINALFILE"
    feh "$FINALFILE"
    ;;
  savecopy)
    mv -f "$TMPFILE" "$FINALFILE"
    wl-copy --type image/png < "$FINALFILE"
    ;;
  save|"")
    mv -f "$TMPFILE" "$FINALFILE"
    ;;
esac
