#!/bin/sh
set -eu # Exit on error (-e) and on undefined variables (-u)

OUTDIR="$HOME/Pictures/Screenshots"
TMPDIR="$XDG_RUNTIME_DIR"
TS="$(date +%Y%m%d_%H%M%S_%3N)"
NAME="${TS}_grim.png"
TMPFILE="$TMPDIR/$NAME"
FINALFILE="$OUTDIR/$NAME"
BODY="$(printf '<img src="file://%s"/>\n%s' "$TMPFILE" "$NAME")"

grim -g "$(slurp)" "$TMPFILE"
CHOICE="$(
  notify-send \
    -a Screenshot \
    -t 9000 \
    -A save=Save \
    -A discard=Discard \
    -A edit=Edit \
    -A copy=Copy \
    -A saveshow='Save & Show' \
    -A savecopy='Save & Copy' \
    "Screenshot Captured" "$BODY"
)"

case "${CHOICE:-}" in
  save|"")
    mv -f "$TMPFILE" "$FINALFILE"
    ;;
  discard)
    rm -f -- "$TMPFILE"
    ;;
  edit)
    mv -f "$TMPFILE" "$FINALFILE"
    swappy -f "$FINALFILE"
    ;;
  copy)
    wl-copy --type image/png < "$TMPFILE"
    rm -f -- "$TMPFILE"
    ;;
  close)
    exit 0
    ;;
  saveshow)
    mv -f "$TMPFILE" "$FINALFILE"
    feh "$FINALFILE"
    ;;
  savecopy)
    mv -f "$TMPFILE" "$FINALFILE"
    wl-copy --type image/png < "$FINALFILE"
    ;;
esac
