#!/usr/bin/env sh

# Make sure it only spawn once
lockdir="${XDG_RUNTIME_DIR:?}/screenshot-locks"
mkdir -p "$lockdir"
lockfile="$lockdir/screenshot_menu.lock"
exec 9>"$lockfile"
flock -n 9 || exit 0

# The remaining script
choice=$(printf 'Fullscreen\nWindow\nRegion\n' | rofi -x11 -dmenu --normal-window -window-title "screenshot" -mesg " Screenshot" -theme ~/.config/rofi/themes/screenshot.rasi)

[ -z "$choice" ] && exit 0

# Release the menu lock after Rofi closes and before executing one of the capture scripts
flock -u 9
exec 9>&-

case "${choice:-}" in
    Fullscreen)
        /home/Zrabbit/.config/shell/script/Screenshot/screenshot_fullscreen
        exit 0
        ;;
    Window)
        /home/Zrabbit/.config/shell/script/Screenshot/screenshot_window
        exit 0
        ;;
    Region)
        /home/Zrabbit/.config/shell/script/Screenshot/screenshot_region
        exit 0
        ;;
esac
