# Use a standard location for the status database
status_path "~/.local/state/pimsync/status/"

storage unistra {
    type webcal
    url https://monemploidutemps.unistra.fr/api/calendar/77878358-8552-493f-8d06-c7e358c03690/export
    collection_id edt_unistra
    # Check every 15 minutes
    interval 900
}

storage holidays_fr {
    type webcal
    url https://etalab.github.io/jours-feries-france-data/ics/jours_feries_alsace-moselle.ics
    collection_id holidays_fr
    # Check every 24 hours
    interval 86400
}

storage local {
    type vdir/icalendar
    path ~/.local/share/calendars
}

pair unistra {
    storage_a unistra
    storage_b local
    collection edt_unistra
    one_way
}

pair holidays_fr {
    storage_a holidays_fr
    storage_b local
    collection holidays_fr
    one_way
}
