# Use a standard location for the status database
status_path "~/.local/state/pimsync/status/"

storage unistra {
    type webcal
    url https://monemploidutemps.unistra.fr/api/calendar/77878358-8552-493f-8d06-c7e358c03690/export
    collection_id edt_unistra
    # Check every 15 minutes
    interval 900
}

storage local {
    type vdir/icalendar
    path ~/.local/share/calendars
}

pair unistra {
    storage_a unistra
    storage_b local
    collection edt_unistra
    one_way
}
