#!/usr/bin/env sh
swaync-client -cp
choice=$(printf '%s\n' No Yes | rofi -x11 -dmenu -normal-window -window-title "confirmbox" -mesg "Confirm to Shutdown" -theme ~/.config/rofi/themes/confirmation-box.rasi)
[ "$choice" = "Yes" ] && hyprctl dispatch "hl.dsp.exec_cmd('hyprshutdown -t Shutting_Down... --post-cmd poweroff')"
