#!/usr/bin/env sh
swaync-client -cp
choice=$(printf '%s\n' No Yes | rofi -x11 -dmenu -normal-window -window-title "confirmbox" -mesg "Hibernate to Disque" -theme ~/.config/rofi/themes/confirmation-box.rasi)
[ "$choice" = "Yes" ] && systemctl hibernate
