#!/usr/bin/env bash
set -uo pipefail

# Print prompt
printf "\033[1;36mOptions:\033[0m\n"
printf "\033[38;5;208m  ⤷ 󰎦  Move .flac/.m4a with its lrc files into Music Directory\033[0m\n"
printf "\033[38;5;208m  ⤷ 󰎩  Fetch YouTube Music\033[0m\n"
printf "\033[38;5;208m  ⤷ 󰎬  Quit\033[0m\n"
printf "\033[1;36mYour choice ›\033[0m "

read -r ans

case "$ans" in
    1)
      mv -v /home/Zrabbit/Downloads/*.flac "/home/Zrabbit/Music/Apple Music/"
      mv -v /home/Zrabbit/Downloads/*.lrc "/home/Zrabbit/Music/lyrics/Apple Music/"
      mv -v /home/Zrabbit/Downloads/YouTube_Music/*.m4a "/home/Zrabbit/Music/YouTube Music/"
      mv -v /home/Zrabbit/Downloads/YouTube_Music/*.lrc "/home/Zrabbit/Music/lyrics/YouTube Music/"
      rmpc update
      exit 0
      ;;
  2)
      printf "\033[1;36mEnter URL ›\033[0m "
      read -r url
      printf "\033[1;36mDo you need lyrics ›\033[0m "
      read -r if_lyrics
      case "$if_lyrics" in
          1|y|Y|yes|YES|o|O|oui|Oui)
              yt-dlp --quiet --write-auto-subs --convert-subs lrc "$url"
              printf "\033[1;36mHere is the files currently under Downloads directory:\033[0m\n"
              ls --color=auto /home/Zrabbit/Downloads/YouTube_Music/
              exit 0
              ;;
          2|n|N|no|NO|non|NON)
              yt-dlp --quiet "$url"
              printf "\033[1;36mHere is the files currently under Downloads directory:\033[0m\n"
              ls --color=auto /home/Zrabbit/Downloads/YouTube_Music/
              printf "\033[1;36mDo you want to move the downloaded audio file into Music directory ›\033[0m "
              read -r if_move_no_lyrics
              case "$if_move_no_lyrics" in
                  1|y|Y|yes|YES|o|O|oui|Oui)
                      mv -v /home/Zrabbit/Downloads/YouTube_Music/*.m4a "/home/Zrabbit/Music/YouTube Music/"
                      rmpc update
                      exit 0
                      ;;
                  2|n|N|no|NO|non|NON)
                      exit 0
                      ;;
              esac
              ;;
      esac
      ;;
  3|q|quit|Q|QUIT)
      exit 0
      ;;
  *) printf "\033[1;31m Not a valid option\033[0m\n"; exit 0 ;;
esac
