#!/bin/sh

# If rmpc is already running, just show/hide the special workspace and exit.
if pgrep -x rmpc >/dev/null 2>&1; then
  hyprctl dispatch togglespecialworkspace rmpc >/dev/null 2>&1
  exit 0
fi

hyprctl dispatch 'hl.dsp.exec_cmd("ghostty --title=rmpc -e rmpc", { workspace = "special:rmpc"})' >/dev/null 2>&1
