#!/usr/bin/env bash
set -euo pipefail

# Template Path
TB_Template=/home/Zrabbit/Projects/FPGA/Template/tb_template.v
TB_MakeFile=/home/Zrabbit/Projects/FPGA/Template/Makefile_template

# Create folders
printf "\033[1;36mProject Name ›\033[0m "
read -r ProjectName
ProjectFolder=/home/Zrabbit/Projects/FPGA/"$ProjectName"
mkdir -p "$ProjectFolder"
cd "$ProjectFolder"
mkdir src/ build/ wave/ tb/

# Create source file
SourceFolder="$ProjectFolder"/src
printf "\033[1;36m%*s\033[0m\n" "$(tput cols)" "" | tr ' ' '='
printf "\033[1;36mCreating Source File...\033[0m\n"
touch "$SourceFolder/top.v"

# Create test bench file
TBFolder="$ProjectFolder"/tb
printf "\033[1;36m%*s\033[0m\n" "$(tput cols)" "" | tr ' ' '='
printf "\033[1;36mCreating a template testbench file...\033[0m\n"
cp "$TB_Template" "$TBFolder/tb_top.v"

# Create Makefile template
printf "\033[1;36mCreating a template Makefile...\033[0m\n"
cp "$TB_MakeFile" "$ProjectFolder/Makefile"
