#!/bin/bash

set -euxo pipefail

HOST_HOME="/home/Zrabbit"
REAL_HOME="/home/Zrabbit"
FAKE_HOME="/home/Steam"

args=(
    --die-with-parent
    --dev-bind /dev /dev
    --proc /proc
    --bind /run /run

    --bind "${FAKE_HOME}" "${REAL_HOME}"
    --chdir "${REAL_HOME}"
    --setenv HOME "$REAL_HOME"

    --ro-bind-try "$HOST_HOME/.config" "$REAL_HOME/.hostConfig"
    --ro-bind-try "$HOST_HOME/.local/share/icons" "$REAL_HOME/.local/share/icons"
    --ro-bind-try "$HOST_HOME/.local/share/themes" "$REAL_HOME/.local/share/themes"

    --unsetenv XDG_CACHE_HOME
    --unsetenv XDG_CONFIG_HOME
    --unsetenv XDG_DATA_HOME
    --unsetenv XDG_STATE_HOME

    --tmpfs /tmp
    --tmpfs /tmp/.X11-unix
)

for dir in /sys /etc /usr /var /opt; do
    args+=(--ro-bind "$dir" "$dir")
done

args+=(
    --symlink usr/bin /bin
    --symlink usr/bin /sbin
    --symlink usr/lib /lib
    --symlink usr/lib /lib64
)

if [[ "${DISPLAY:-}" == :* ]]; then
    display_nr="${DISPLAY/#:/}"    # Strip leading ":"
    display_nr="${display_nr/%.*}" # Strip screen suffix
    local_socket=/tmp/.X11-unix/X"${display_nr}"
    args+=(--ro-bind-try "${local_socket}" "${local_socket}")
fi

if [[ "${XAUTHORITY:-}" == /tmp/* ]]; then
    args+=(--ro-bind-try "${XAUTHORITY}" "${XAUTHORITY}")
fi

exec bwrap "${args[@]}" -- /usr/bin/r2modman "$@"
