#!/bin/bash

set -euo pipefail

HOST_HOME="/home/Zrabbit"
REAL_HOME="/home/Zrabbit"
FAKE_HOME="/home/Steam"

args=(
    --die-with-parent
    --dev-bind /dev /dev
    --proc /proc
    --bind /run /run

    --bind "${FAKE_HOME}" "${REAL_HOME}"
    --symlink Zrabbit /home/Steam
    --chdir "${REAL_HOME}"

    --ro-bind-try "$HOST_HOME/.config" "$REAL_HOME/.hostConfig"
    --ro-bind-try "$HOST_HOME/.local/share/icons" "$REAL_HOME/.local/share/icons"
    --ro-bind-try "$HOST_HOME/.local/share/themes" "$REAL_HOME/.local/share/themes"

    --setenv HOME "$REAL_HOME"
    --setenv APPIMAGE_EXTRACT_AND_RUN 1
    --setenv XDG_CONFIG_HOME "$REAL_HOME/.config"
    --setenv XDG_DATA_HOME "$REAL_HOME/.local/share"
    --setenv XDG_CACHE_HOME "$REAL_HOME/.cache"
    --setenv XDG_STATE_HOME "$REAL_HOME/.local/state"

    --tmpfs /tmp
    --tmpfs /tmp/.X11-unix
)

for dir in /sys /etc /usr /var /opt; do
    args+=(--ro-bind "$dir" "$dir")
done

args+=(
    --symlink usr/bin /bin
    --symlink usr/bin /sbin
    --symlink usr/lib /lib
    --symlink usr/lib /lib64
)

if [[ "${DISPLAY:-}" == :* ]]; then
    display_nr="${DISPLAY/#:/}"    # Strip leading ":"
    display_nr="${display_nr/%.*}" # Strip screen suffix
    local_socket=/tmp/.X11-unix/X"${display_nr}"
    args+=(--ro-bind-try "${local_socket}" "${local_socket}")
fi

if [[ "${XAUTHORITY:-}" == /tmp/* ]]; then
    args+=(--ro-bind-try "${XAUTHORITY}" "${XAUTHORITY}")
fi

exec bwrap "${args[@]}" -- \
    /home/Zrabbit/Applications/WowUp-CF.AppImage "$@"
